### ISSUE TITLE
Provide better MySQL config examples

### ISSUE THREAD

**Issue by melody-rs** [AppleDash/SaneEconomy#108]
Currently, I'm struggling to properly set MySQL up as a backend (Because I want the eco to sync over my servers, I'm using bungee) but I can't seem to get the formatting right. It's valid YAML but the plugin rejects it. I can't seem to figure out how to properly format and indent my config, and the config examples in the wiki aren't of much help since they just provide the valid options and not what order they should go in, etc.
Here is my config.
```yml
# Settings pertaining to the backend. Check the wiki for valid values here.
backend:
  type: mysql
  hostname: 'localhost'
  port: '3306'
  username: 'root'
  password: '*****'
  databaseName: 'hex'
  prefix: 'economy_'
currency:
  name:
    singular: birbohex
    plural: hex
  format: '0.00'
  grouping: 3
  grouping-separator: ','
chat:
  prefix: '&b[&9HEX&b]&r '
economy:
  start-balance: 100.0 # If this is greater than zero, players will be given this amount on their first join.
  notify-start-balance: true # Whether to send players a message when they receive their starting balance.
  server-account: '$SERVER$' # Economy operations on an account with this name will appear to have an infinite balance.
  baltop-update-interval: 300 # How often, in seconds, to reload the content of /baltop from the database.
  notify-admin-give: false # Whether to notify players when /ecoadmin give is used on them.
  notify-admin-take: false # Whether to notify players when /ecoadmin take is used on them.
  notify-admin-set: false # Whether to notify players when /ecoadmin set is used on them.
  pay-offline-players: true # Whether to allow paying offline players or not.
multi-server-sync: true # Experimental balance syncing without player rejoins, across BungeeCord networks.
update-check: true # Whether to check for updates to the plugin and notify admins about them.
locale-override: false # Whether to force the server's locale to be en_US.
debug: false # Debug mode, leave this set to false.
metrics: true # Whether to send anonymous metrics about the plugin's usage back to the developers, useful for fixing crashes.
```
